export const Services = [
	{
		name: "VIP HOT",
		image: "https://cdn.ereemby.com/attachments/17115109529541805-imagem.png",
		desc: "Satisfação garantida! 😈🔞🔥",
		price: 50,
		discount: 26,
		total: 37,
		link: "",
		time: "30 Dias",
		stock: 1,
		details: [ 'Mais de 10000 mídias no VIP mais completo HotFans', 'Acesso por 30 dias a TODOS os conteúdos EXCLUSIVOS HotFans' ],
		content: [ 'Vip only fans', 'Vip lives vazadas', 'Vip vazados' ],
	},
	{
		name: "VIP ONLYFANS",
		image: "https://cdn.ereemby.com/attachments/17115110732083964-imagem.png",
		desc: "Exclusividade total! 😈",
		price: 40,
		discount: 32,
		total: 27,
		link: "",
		time: "30 Dias",
		stock: 1,
		details: [ 'Mais de 8000 mídias no VIP mais exclusivo do brasil. Veja aquela menina bonita do insta ou tiktok aqui', 'Acesso por 30 dias a TODOS os conteúdos EXCLUSIVOS do vip only fans, contém apenas assinaturas de meninas famosas ou nao do onlyfans' ],
		content: [ 'Vip only fans' ],
	},
	{
		name: "VIP VAZADOS",
		image: "https://cdn.ereemby.com/attachments/17115109529541805-imagem.png",
		desc: "Vazadinhos na net! 😈",
		price: 35,
		discount: 35,
		total: 22.70,
		link: "",
		time: "30 Dias",
		stock: 1,
		details: [ 'Mais de 5000 mídias no VIP mais exclusivo do brasil. Vazou na net! Namorado postou video da namorada puta, foi na casa do amigo e quis gravar tudo isso e muito mais!', 'Acesso por 30 dias a TODOS os conteúdos EXCLUSIVOS do vip vazados, Apenas vídeos vazados nos momentos mais verdadeiros da vida (que tesão)' ],
		content: [ 'Vip vazados' ],
	},
	{
		name: "VIP LIVES",
		image: "https://cdn.ereemby.com/attachments/17115111112919005-imagem.png",
		desc: "Vazadinhos na net! 😈",
		price: 25,
		discount: 32,
		total: 17,
		link: "",
		time: "30 Dias",
		stock: 1,
		details: [ 'Mais de 3000 mídias no VIP mais exclusivo do brasil (+9k horas vazadas). Lives vazadas ao vivo com muito conteúdo esperando vc, as meninas se jogam!', 'Acesso por 30 dias a TODOS os conteúdos EXCLUSIVOS do vip lives vazadas, apenas lives' ],
		content: [ 'Vip lives vazadas' ],
	},
];